services:
  # 前端服務配置
  frontend:
    build:
      context: ./frontend  # 使用 ./frontend 目錄中的 Dockerfile 構建映像
      dockerfile: Dockerfile.dev  # 指定使用的 Dockerfile 文件名
    container_name: frontend  # 指定容器名稱，方便識別
    ports:
      - "5173:5173"  # 將容器的 5173 端口映射到主機的 5173 端口
    volumes:
      - ./frontend:/app  # 掛載本地前端代碼到容器中，支持即時更新
      - /app/node_modules  # 將容器內的 node_modules 排除在掛載外，避免被本地覆蓋
    # depends_on:
    #   - backend  # 確保後端服務先啟動
    environment:
      - NODE_ENV=development  # 設置環境變量
      - VITE_API_URL=http://localhost:3000  # 設置 API 的基礎 URL
    restart: unless-stopped  # 除非手動停止，否則繼續重啟
    
  # 後端服務配置
  backend:
    build:
      context: ./backend  # 使用 ./backend 目錄中的 Dockerfile 構建映像
      dockerfile: Dockerfile.dev  # 指定使用的 Dockerfile 文件名
    container_name: backend  # 指定容器名稱
    ports:
      - "3000:3000"  # 將容器的 3000 端口映射到主機的 3000 端口
    volumes:
      - ./backend:/app  # 掛載本地後端代碼到容器中，支持即時更新
      - /app/node_modules  # 保護容器內的 node_modules
    # depends_on:
    #   - db  # 確保數據庫服務先啟動
    environment:
      - NODE_ENV=development  # 設置環境變量
      # - DB_HOST=db  # 注意這裡使用服務名稱作為主機名，而非 localhost
      # - DB_USER=root
      # - DB_PASSWORD=password  # 在生產環境中應使用更安全的密碼
      # - DB_NAME=myapp
      # - DB_PORT=3306
      # - LANG=C.UTF-8
    restart: unless-stopped  # 自動重啟策略