-- 安裝 trgm 模組
CREATE EXTENSION IF NOT EXISTS pg_trgm;
-- 安裝 uuid-ossp 模組
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 發布者
CREATE TABLE "posters" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nickname" VARCHAR NOT NULL,
  "avatar_url" VARCHAR,
  "game_id" VARCHAR NOT NULL,
  "created_at" TIMESTAMP DEFAULT (NOW()),
  "updated_at" TIMESTAMP DEFAULT (NOW())
);
CREATE UNIQUE INDEX "idx_posters" ON "posters" ("game_id", "nickname");

-- 發布者-聯絡方式
CREATE TABLE "poster_contacts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "poster_id" INTEGER NOT NULL REFERENCES "posters" ("id"),
  "type" contact_type NOT NULL,
  "value" VARCHAR NOT NULL,
  "created_at" TIMESTAMP DEFAULT (NOW()),
  "updated_at" TIMESTAMP DEFAULT (NOW())
);
CREATE UNIQUE INDEX "idx_poster_contacts" ON "poster_contacts" ("poster_id", "type");

-- 商品
CREATE TABLE "commodities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" commodity_type NOT NULL,
  "remark" text,
  "tags" VARCHAR[],
  "created_at" TIMESTAMP DEFAULT (NOW()),
  "updated_at" TIMESTAMP DEFAULT (NOW())
);
CREATE INDEX "idx_commodities" ON "commodities" ("id", "type");

-- 商品-金幣
CREATE TABLE "coin_commodities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "commodity_id" INTEGER UNIQUE NOT NULL REFERENCES "commodities" ("id"),
  "coin_ratio_value" decimal NOT NULL,
  "coin_ratio_currency" currency_type NOT NULL,
  "amount" decimal NOT NULL,
  "trans_min_limit" INTEGER NOT NULL,
  "created_at" TIMESTAMP DEFAULT (NOW()),
  "updated_at" TIMESTAMP DEFAULT (NOW())
);
CREATE INDEX "idx_coin_commodities" ON "coin_commodities" ("id", "coin_ratio_currency", "coin_ratio_value", "amount");

-- 商品-外觀
CREATE TABLE "appearance_commodities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "commodity_id" INTEGER UNIQUE NOT NULL REFERENCES "commodities" ("id"),
  "name" VARCHAR NOT NULL,
  "category" appearance_type NOT NULL,
  "amount" INTEGER NOT NULL,
  "price_currency" currency_type NOT NULL,
  "price_value" decimal NOT NULL,
  "created_at" TIMESTAMP DEFAULT (NOW()),
  "updated_at" TIMESTAMP DEFAULT (NOW())
);
CREATE INDEX "idx_appearance_commodities_name" ON "appearance_commodities" USING GIN ("name" gin_trgm_ops);
CREATE INDEX "idx_appearance_commodities" ON "appearance_commodities" ("id", "category", "name", "price_currency", "price_value");

-- 商品-角色
CREATE TABLE "character_commodities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "commodity_id" INTEGER UNIQUE NOT NULL REFERENCES "commodities" ("id"),
  "sect_list" sect_type[] NOT NULL,
  "inner_skill_list" inner_skill_type[] NOT NULL,
  "body_type_list" body_type[] NOT NULL,
  "camp_list" camp_type[] NOT NULL,
  "level" INTEGER NOT NULL,
  "info_no_debt" boolean NOT NULL,
  "info_need_change_name" boolean NOT NULL,
  "info_need_transferred" boolean NOT NULL,
  "info_need_full_level" boolean NOT NULL,
  "price_currency" currency_type NOT NULL,
  "price_value" INTEGER NOT NULL,
  "image_list" VARCHAR[],
  "battle_rank_score" INTEGER,
  "estate_rank_score" INTEGER,
  "endless_battle_value_energy" INTEGER,
  "endless_battle_value_stamina" INTEGER,
  "accomplishment_score" INTEGER,
  "pet_score" INTEGER,
  "created_at" TIMESTAMP DEFAULT (NOW()),
  "updated_at" TIMESTAMP DEFAULT (NOW())
);
CREATE INDEX "idx_character_commodities" ON "character_commodities" ("id", "sect_list", "inner_skill_list", "body_type_list", "camp_list", "accomplishment_score", "price_currency", "price_value");

-- 商品-角色-裝分
CREATE TABLE "character_gear_scores" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "character_commodity_id" INTEGER NOT NULL REFERENCES "character_commodities" ("id"),
  "inner_skill" inner_skill_type,
  "type" gear_type NOT NULL,
  "score" INTEGER,
  "created_at" TIMESTAMP DEFAULT (NOW()),
  "updated_at" TIMESTAMP DEFAULT (NOW())
);
CREATE UNIQUE INDEX ON "character_gear_scores" ("character_commodity_id", "inner_skill", "type");

-- 商品-角色-競技場分數
CREATE TABLE "character_arena_scores" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "character_commodity_id" INTEGER NOT NULL REFERENCES "character_commodities" ("id"),
  "type" arena_type NOT NULL,
  "score" INTEGER,
  "created_at" TIMESTAMP DEFAULT (NOW()),
  "updated_at" TIMESTAMP DEFAULT (NOW())
);
CREATE UNIQUE INDEX ON "character_arena_scores" ("character_commodity_id", "type");

-- 商品-角色-外觀數量
CREATE TABLE "character_skin_counts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "character_commodity_id" INTEGER NOT NULL REFERENCES "character_commodities" ("id"),
  "type" skin_type NOT NULL,
  "value" INTEGER,
  "created_at" TIMESTAMP DEFAULT (NOW()),
  "updated_at" TIMESTAMP DEFAULT (NOW())
);
CREATE UNIQUE INDEX ON "character_skin_counts" ("character_commodity_id", "type");

-- 交易
CREATE TABLE "transactions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" VARCHAR(20) UNIQUE,
  "token" uuid DEFAULT uuid_generate_v4() UNIQUE NOT NULL,
  "type" transaction_type NOT NULL,
  "status" transaction_status_type NOT NULL,
  "methods" transaction_method_type[] NOT NULL,
  "commodity" INTEGER NOT NULL REFERENCES "commodities" ("id"),
  "posted_by" INTEGER NOT NULL REFERENCES "posters" ("id"),
  "created_at" TIMESTAMP DEFAULT (NOW()),
  "updated_at" TIMESTAMP DEFAULT (NOW())
);
CREATE INDEX "idx_transactions_token" ON "transactions" ("token");
CREATE INDEX "idx_transactions_methods" ON "transactions" USING GIN ("methods");
CREATE INDEX "idx_transactions" ON "transactions" ("type", "status", "commodity", "posted_by", "created_at", "updated_at");
